name: quik_locale
description: Manual, typed, effortless Flutter localization plugin. Define translations as Dart constants with full IDE support and type safety.
version: 1.0.1
homepage: https://vignaraj.dev
repository: https://github.com/vignarajj/quik_locale
issue_tracker: https://github.com/vignarajj/quik_locale/issues

environment:
  sdk: ^3.8.1
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
  test: ^1.24.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
